START TRANSACTION;
  ALTER TABLE "users" ADD "phone" CHARACTER VARYING;
  ALTER TABLE "users" ADD "gender" CHARACTER VARYING;
  ALTER TABLE "users" ADD "stack" CHARACTER VARYING;
  ALTER TABLE "users" ADD "rate" INT DEFAULT 800;
  ALTER TABLE "users" ADD "rating" INT DEFAULT 1;
COMMIT;